### ISSUE TITLE
How to configure extension options

### ISSUE THREAD

**Issue by mfeif** [avanov/Plim#40]
For example, to use the various extensions and other optional features in markdown.

For example, I'd like to use the "smartypants" extension.

Does one have to create a custom extension with the right params?

Thanks

**Comment by avanov** [comment]
Hi @mfeif 

Currently, Plim does not have an API for extending the default markdown parser and, as a quick solution, I can suggest writing your own [custom extension](http://plim.readthedocs.org/en/latest/en/extensions.html#extending-plim-with-custom-parsers). In your example, it would look like this:

```python
import re
import markdown2
from plim import lexer, preprocessor_factory

SMARTYMARK_EXTRAS = ["smartypants"]
SMARTYMARK_BLOCK_RE = re.compile('-\s*(?P<section>smartymark)\s*')

# Please refer to source docs with regard to parser's API:
# https://github.com/avanov/Plim/blob/0.9.10/plim/lexer.py#L141
def parse_smartymark(indent_level, current_line, matched, source, syntax):
    parsed_block, tail_indent, tail_line, source = lexer.parse_explicit_literal_no_embedded(
        indent_level,
        lexer.LITERAL_CONTENT_PREFIX,
        matched,
        source,
        syntax
    )
    parsed_block = markdown2.markdown(parsed_block, extras=SMARTYMARK_EXTRAS)
    return parsed_block.strip(), tail_indent, tail_line, source

MY_PARSERS = [
    (SMARTYMARK_BLOCK_RE, parse_smartymark),
]

# Create a custom Plim preprocessor that can be fed to Mako API
preprocessor = preprocessor_factory(custom_parsers=MY_PARSERS, syntax='mako')
```
Once you have a custom preprocessor with your own extensions, you can use it instead of the default one.

Personally, I prefer custom preprocessors to API extensions, though you may find this approach cumbersome. Therefore, feel free to suggest an API extension as you'd like to see it. I can't promise to accept them, but at least we could discuss it and review possible benefits.

**Comment by mfeif** [comment]
Thanks so much for your reply.

I proceeded last night to find basically the same solution, though a little more drastic.

https://github.com/mfeif/pygreen/blob/master/plim_hook.py

I truly appreciate the quick response, and am glad to know that I found what is in your opinion the right answer.

**Comment by avanov** [comment]
I would say that you had done it even better by replacing the default ``-md`` block parser with your own. This is not even a hack, but rather a feature. Custom parsers take precedence over default ones, and your users won't be confused by "custom-vs-default" choice.

Cheers!
